builder:
  track: dev

labels:
  app-group: estafette-ci
  type: storage
  team: estafette-team
  language: helm

version:
  semver:
    major: 1
    minor: 0

stages:
  validate-manifest:
    image: extensions/helm:dev
    action: diff
    credentials: gke-tooling-estafette
    repoUrl: https://charts.cockroachdb.com/
    chart: cockroachdb
    version: 5.0.5
    namespace: estafette-ci
    release: cockroachdb

releases:
  tooling-estafette:
    actions:
    - name: diff
    - name: install
    stages:
      deploy:
        image: extensions/helm:dev
        repoUrl: https://charts.cockroachdb.com/
        chart: cockroachdb
        version: 5.0.5
        namespace: estafette-ci
        release: cockroachdb
        timeout: 300s
        values: |-
          conf:
            locality: continent=europe,country=belgium,region=europe-west1
          statefulset:
            annotations:
              prometheus.io/scrape: "true"
              prometheus.io/path: "/_status/vars"
              prometheus.io/port: "8080"
              prometheus.io/scheme: "http"
            resources:
              requests:
                cpu: 1000m
                memory: 12Gi
              limits:
                memory: 12Gi
            tolerations:
            - effect: NoSchedule
              key: cloud.google.com/gke-preemptible
              operator: Equal
              value: "true"
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 10
                preference:
                  matchExpressions:
                  - key: cloud.google.com/gke-preemptible
                    operator: In
                    values:
                    - "true"
            podAntiAffinity:
              type: hard
          tls:
            enabled: true
          service:
            public:
              type: NodePort
              annotations:
                prometheus.io/probe: "true"
                prometheus.io/probe-path: "/health"
                beta.cloud.google.com/backend-config: '{"default": "cockroachdb-admin"}'
                service.alpha.kubernetes.io/app-protocols: '{"http":"HTTPS"}'
                cloud.google.com/neg: '{"ingress": true}'
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: "gce"
              kubernetes.io/ingress.allow-http: "false"
              estafette.io/cloudflare-dns: "true"
              estafette.io/cloudflare-proxy: "false"
              estafette.io/cloudflare-hostnames: "estafette.secret(0JGttv0haO1F4r_v.12nJe8twdMf_pVBBmzjsEAPrc5zYy2MXR74_hLt5-Oq5MyRq1MTGAZbb9H6bdpfd)"
            paths: ['/*']
            hosts:
            - estafette.secret(0JGttv0haO1F4r_v.12nJe8twdMf_pVBBmzjsEAPrc5zYy2MXR74_hLt5-Oq5MyRq1MTGAZbb9H6bdpfd)
            tls:
            - hosts: [estafette.secret(0JGttv0haO1F4r_v.12nJe8twdMf_pVBBmzjsEAPrc5zYy2MXR74_hLt5-Oq5MyRq1MTGAZbb9H6bdpfd)]
              secretName: cockroachdb-letsencrypt-certificate
          storage:
            persistentVolume:
              enabled: true
              size: 50Gi
              storageClass: fast