builder:
  track: dev

labels:
  app-group: estafette-ci
  type: storage
  team: estafette-team
  language: helm

version:
  semver:
    major: 1
    minor: 0

stages:
  validate-manifest:
    image: extensions/helm:dev
    action: diff
    credentials: gke-tooling-estafette
    repoUrl: https://charts.cockroachdb.com/
    chart: cockroachdb
    version: 6.0.3
    namespace: estafette-ci
    release: cockroachdb

releases:
  tooling-estafette:
    actions:
    - name: diff
    - name: install
    stages:
      deploy:
        image: extensions/helm:dev
        repoUrl: https://charts.cockroachdb.com/
        chart: cockroachdb
        version: 6.0.3
        namespace: estafette-ci
        release: cockroachdb
        timeout: 300s
        values: |-
          image:
            credentials:
              registry: docker.io
              username: estafette.secret(mRAxkLM78PZ6pMrO.Y0-dvbf8RCm-snraQD_6p-_wNmQETXO4vhdk35DqEQ==.cFSIo6vmCSOzqjzTVy7pu6zX-oz-bF5AokZ_zJv84DdV-B8TQc5R-qEbRaH7YnWm)
              password: estafette.secret(fZUqRMtSTKYxBPtc.0qJhv0XK_WLTxlD4xZwDB7j7mzh891frdGGiw-v6Lzly1tAgDch_UDCizq7BQoKy4YSGPg==.0a92tQHL4mORk0mog8VWUOi_wmU3rVulL3X4x7CkeT1UZduJ6MnFF4z1lNwk773H)
          conf:
            locality: continent=europe,country=belgium,region=europe-west1
          statefulset:
            annotations:
              prometheus.io/scrape: "true"
              prometheus.io/path: "/_status/vars"
              prometheus.io/port: "8080"
              prometheus.io/scheme: "https"
            resources:
              requests:
                cpu: 2000m
                memory: 12Gi
              limits:
                memory: 12Gi
            tolerations:
            - effect: NoSchedule
              key: cloud.google.com/gke-preemptible
              operator: Equal
              value: "true"
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 10
                preference:
                  matchExpressions:
                  - key: cloud.google.com/gke-preemptible
                    operator: In
                    values:
                    - "true"
            podAntiAffinity:
              type: hard
          tls:
            enabled: true
          service:
            public:
              type: NodePort
              annotations:
                cloud.google.com/neg: '{"ingress": true}'
          ingress:
            enabled: true
            annotations:
              estafette.io/cloudflare-dns: "true"
              estafette.io/cloudflare-proxy: "false"
              estafette.io/cloudflare-hostnames: "estafette.secret(0JGttv0haO1F4r_v.12nJe8twdMf_pVBBmzjsEAPrc5zYy2MXR74_hLt5-Oq5MyRq1MTGAZbb9H6bdpfd)"
            paths: ['/*']
            hosts:
            - estafette.secret(0JGttv0haO1F4r_v.12nJe8twdMf_pVBBmzjsEAPrc5zYy2MXR74_hLt5-Oq5MyRq1MTGAZbb9H6bdpfd)
            tls:
            - hosts: [estafette.secret(0JGttv0haO1F4r_v.12nJe8twdMf_pVBBmzjsEAPrc5zYy2MXR74_hLt5-Oq5MyRq1MTGAZbb9H6bdpfd)]
              secretName: estafette.secret(OnoVr6TSFAhoZTYr.r-bTn9Un9lyfIS9B6jJGFfE94rziQi_oeG6snh1iYTpooqvDx_-5ANcYe47FLKKmSpFcwn2svB5woIOhu-M=.vP3Ggck99UyYLXJB_WtQGvgt9bi_RW3ndmiwmhBpdyH-Pn1JZJ6QoE2sLQGiFl-5)
          storage:
            persistentVolume:
              enabled: true
              size: 50Gi
              storageClass: fast
          iap:
            enabled: true
            clientId: estafette.secret(LEYF3nen80kTaM1f.R5nuGCATjmkFBBns5hx1xE3y-xAJgBqNnJel_RAJxhij0zG894845k8AZvV4koJz2PC6wVorfNrapyrYusEqWhEmJ2SkqwgnpzG2TAsfWWeWeCxKr9eVzg==.FcKoR2BDkjhaXQ6wuAclk1rj_AQfkxiFmta87kQXwxxwuRbs9Y1nbVP8f5a8yn8F)
            clientSecret: estafette.secret(RIEgeaySMl_gBXEN.k9lXkMJpiGmlI0iJhsOuyKYDdlmGOah1MAi4u15OKoSWLPn456IdAw==.kdoWydBCyECjBzPYsc6rwJxBcE7NbpV9jApS0ittodESXEMuICJGNceEHKg0kJ25)