builder:
  track: dev
  medium: memory

labels:
  app-group: estafette-ci
  type: storage
  team: estafette-team
  language: helm

version:
  semver:
    major: 1
    minor: 0
    patch: 0
    labelTemplate: '{{branch}}-{{auto}}'
    releaseBranch: 1.0.0

stages:
  validate-manifest:
    image: extensions/gke-yaml:dev
    credentials: gke-tooling-estafette
    namespace: estafette-ci
    manifests:
    - kubernetes.yaml
    placeholders:
      APP_NAME: cockroachdb
      NAMESPACE: estafette
      TEAM_NAME: estafette
      HOSTNAMES: estafette.secret(0JGttv0haO1F4r_v.12nJe8twdMf_pVBBmzjsEAPrc5zYy2MXR74_hLt5-Oq5MyRq1MTGAZbb9H6bdpfd)
      ENABLE_CLOUDFLARE_DNS: true
      JOIN_REMOTE_HOSTS: ',cockroachdb-0.cockroachdb.estafette.svc.cluster.local,cockroachdb-1.cockroachdb.estafette.svc.cluster.local'
      COCKROACHDB_VERSION: v20.2.4
      REPLICAS: 3
      CPU_REQUEST: 1000m
      MEMORY_REQUEST: 12Gi
      MEMORY_LIMIT: 12Gi
      STORAGE_CLASS: fast
      PVC_SIZE: 50Gi
      LOCALITY: continent=europe,country=belgium,region=europe-west1,zone=europe-west1-c
      IAP_OAUTH_CLIENT_ID: estafette.secret(rJjOuzaXarfMhp9j.0nfQMauGykd-Cfu6eNBJW99Toszx6uf1tzw_6q62kmZ6mWceXqA1KPgXhO-SzynibLG0hKjCKVrHahdAM36ssjWWw9-z7sKOE36MfaejL48VZru13LXNtrpivYErUdk5f9VUWxWt_dLpwj6gtJZf9A==.-0rtIJCesV1cDp2oReBPCPZw7tGT0cL6v30Vvq6Zx3bgmKrIPeDu2SXucSLJr8v7)
      IAP_OAUTH_CLIENT_SECRET: estafette.secret(iPS8QdKCO5TGlWfo.lEwkMhvKFokp9ypzY3cN2CDa4y4X5Gu-Xk4IqrmYImJXCUwzfNVmhDaYGHlhIPyc.qXI_ayP_XKAk8XVmQ1U9jhfm-yBa6zzvVlItoJS2DHKhbPmvGJjegDrfFO8dkU2z)
    statefulsets:
    - cockroachdb
    dryrun: true

releases:
  tooling-estafette:
    clone: true
    stages:
      deploy:
        image: extensions/gke-yaml:dev
        credentials: gke-tooling-estafette
        namespace: estafette-ci
        manifests:
        - kubernetes.yaml
        placeholders:
          APP_NAME: cockroachdb
          NAMESPACE: estafette
          TEAM_NAME: estafette
          HOSTNAMES: estafette.secret(0JGttv0haO1F4r_v.12nJe8twdMf_pVBBmzjsEAPrc5zYy2MXR74_hLt5-Oq5MyRq1MTGAZbb9H6bdpfd)
          ENABLE_CLOUDFLARE_DNS: true
          JOIN_REMOTE_HOSTS: ',cockroachdb-0.cockroachdb.estafette.svc.cluster.local,cockroachdb-1.cockroachdb.estafette.svc.cluster.local'
          COCKROACHDB_VERSION: v20.2.4
          REPLICAS: 3
          CPU_REQUEST: 1000m
          MEMORY_REQUEST: 12Gi
          MEMORY_LIMIT: 12Gi
          STORAGE_CLASS: fast
          PVC_SIZE: 50Gi
          LOCALITY: continent=europe,country=belgium,region=europe-west1,zone=europe-west1-c
          IAP_OAUTH_CLIENT_ID: estafette.secret(rJjOuzaXarfMhp9j.0nfQMauGykd-Cfu6eNBJW99Toszx6uf1tzw_6q62kmZ6mWceXqA1KPgXhO-SzynibLG0hKjCKVrHahdAM36ssjWWw9-z7sKOE36MfaejL48VZru13LXNtrpivYErUdk5f9VUWxWt_dLpwj6gtJZf9A==.-0rtIJCesV1cDp2oReBPCPZw7tGT0cL6v30Vvq6Zx3bgmKrIPeDu2SXucSLJr8v7)
          IAP_OAUTH_CLIENT_SECRET: estafette.secret(iPS8QdKCO5TGlWfo.lEwkMhvKFokp9ypzY3cN2CDa4y4X5Gu-Xk4IqrmYImJXCUwzfNVmhDaYGHlhIPyc.qXI_ayP_XKAk8XVmQ1U9jhfm-yBa6zzvVlItoJS2DHKhbPmvGJjegDrfFO8dkU2z)
        statefulsets:
        - cockroachdb