apiVersion: v1
kind: Namespace
metadata:
  name: ${NAMESPACE}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: ${APP_NAME}
  namespace: ${NAMESPACE}
  labels:
    app: ${APP_NAME}
    team: ${TEAM_NAME}
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: cockroachdb
    meta.helm.sh/release-namespace: estafette-ci
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: ${APP_NAME}
  labels:
    app: ${APP_NAME}
    team: ${TEAM_NAME}
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: cockroachdb
    meta.helm.sh/release-namespace: estafette-ci
rules:
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  verbs:
  - create
  - get
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: ${APP_NAME}
  namespace: ${NAMESPACE}
  labels:
    app: ${APP_NAME}
    team: ${TEAM_NAME}
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: cockroachdb
    meta.helm.sh/release-namespace: estafette-ci
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ${APP_NAME}
subjects:
- kind: ServiceAccount
  name: ${APP_NAME}
  namespace: ${NAMESPACE}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: ${APP_NAME}
  labels:
    app: ${APP_NAME}
    team: ${TEAM_NAME}
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: cockroachdb
    meta.helm.sh/release-namespace: estafette-ci
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ${APP_NAME}
subjects:
- kind: ServiceAccount
  name: ${APP_NAME}
  namespace: ${NAMESPACE}